### ISSUE TITLE
error: use of unresolved identifier 'exit'

### ISSUE THREAD

**Issue by erkekin** [yonaskolb/Beak#9]
got this at first try, after copying and pasting beak.swift from the example in README.md

**$ beak run install**                                                       
```
Compile Swift Module 'BeakFile' (1 sources)
**/Users/----/Documents/beak/builds/_Users_icterra/Sources/BeakFile/main.swift:20:5: error: use of unresolved identifier 'exit'
    exit(1)
    ^~~~**

error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/----/Documents/beak/builds/_Users_icterra/.build/debug.yaml main
```

**Comment by yonaskolb** [comment]
Ah yes, I see. Because the functions are throwing the generated function call includes some error handling which has an exit, which requires an import of Foundation.

```
do {
    try \(functionCall)
} catch {
    print(error)
    exit(1)
}
```

I should automatically add the import if it's missing. In the meantime simply add `import Foundation` into your script.

**Comment by yonaskolb** [comment]
I've documented this for now https://github.com/yonaskolb/Beak/commit/654798052d4f2efbbfba11154f21f340db66676d
